# Generated by Django 3.2 on 2022-12-08 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Должность')),
                ('department', models.CharField(max_length=50, verbose_name='Отдел')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='ФИО сотрудника')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('job_title', models.CharField(max_length=50, verbose_name='Должность сотрудника')),
                ('salary', models.IntegerField(verbose_name='Зарплата')),
                ('cody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cody.cody')),
            ],
        ),
    ]
