# Generated by Django 3.2 on 2022-12-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cody', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
    ]
