# Generated by Django 3.2 on 2022-12-09 10:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cody', '0003_alter_employee_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cody',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cody.cody'),
        ),
    ]
